name = "1001terminal-worker"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[durable_objects]
bindings = [
  { name = "GEX_HISTORY_DO", class_name = "HeatmapBuilderDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "HeatmapBuilderDO" ]

# --- OPTIMIZED CRON ---
# Run every minute (*),
# But ONLY during hours 11 through 23 UTC (approx 6am - 6pm EST),
# And ONLY on Monday through Friday (1-5).
[triggers]
crons = ["* 11-23 * * 1-5"]